version: 2

updates:
    ## Test 1
    - package-ecosystem: "npm"
      directory: "/test1"
      open-pull-requests-limit: 1
      allow:
          - dependency-type: "all"
      commit-message:
          prefix: "dependabot notification"
          include: "scope"
    ## Test 2
    - package-ecosystem: "npm"
      directory: "/test2/dir1"
      open-pull-requests-limit: 1
      allow:
          - dependency-type: "all"
      commit-message:
          prefix: "dependabot notification"
          include: "scope"
    ## Test 3
    - package-ecosystem: "npm"
      directory: "/test3/dir1/dir2"
      open-pull-requests-limit: 1
      allow:
          - dependency-type: "all"
      commit-message:
          prefix: "dependabot notification"
          include: "scope"
